version: "3"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    links:
      - mongo
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "80:80"
    environment:
      MONGO_INITDB_DATABASE: api
    volumes:
      - data-volume:/data/db
volumes:
  data-volume:
