version: "3"
services:
  api:
    networks:
        flywell-onboarding:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    links:
      - mongo
  mongo:
    networks:
        flywell-onboarding:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: api
    volumes:
      - data-volume:/data/db

  minio:  
    networks:
       flywell-onboarding:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
     - MINIO_ROOT_USER
     - MINIO_ROOT_PASSWORD
    volumes:
      - minio_storage:/data
    command: server --console-address ":9001" /data

volumes:
  data-volume:
  minio_storage: {}

networks:
  flywell-onboarding:
